from __future__ import annotations

from collections.abc import Mapping
from io import BytesIO
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from typing_extensions import Self

from .. import types
from ..models.style_enum import StyleEnum
from ..types import UNSET, File, Unset

T = TypeVar("T", bound="ExerciseImageRequest")


@_attrs_define
class ExerciseImageRequest:
    """ExerciseImage serializer

    Attributes:
        exercise (int):
        image (File): Only JPEG, PNG and WebP formats are supported
        is_main (bool | Unset):
        style (StyleEnum | Unset): * `1` - Line
            * `2` - 3D
            * `3` - Low-poly
            * `4` - Photo
            * `5` - Other
        license_ (int | Unset):
        license_title (str | Unset):
        license_object_url (str | Unset):
        license_author (str | Unset): If you are not the author, enter the name or source here.
        license_author_url (str | Unset):
        license_derivative_source_url (str | Unset): Note that a derivative work is one which is not only based on a
            previous work, but which also contains sufficient new, creative content to entitle it to its own copyright.
        is_ai_generated (bool | Unset): Check if this image was generated by AI
    """

    exercise: int
    image: File
    is_main: bool | Unset = UNSET
    style: StyleEnum | Unset = UNSET
    license_: int | Unset = UNSET
    license_title: str | Unset = UNSET
    license_object_url: str | Unset = UNSET
    license_author: str | Unset = UNSET
    license_author_url: str | Unset = UNSET
    license_derivative_source_url: str | Unset = UNSET
    is_ai_generated: bool | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        exercise = self.exercise

        image = self.image.to_tuple()

        is_main = self.is_main

        style: str | Unset = UNSET
        if not isinstance(self.style, Unset):
            style = self.style.value

        license_ = self.license_

        license_title = self.license_title

        license_object_url: str | Unset
        if isinstance(self.license_object_url, Unset):
            license_object_url = UNSET
        else:
            license_object_url = self.license_object_url

        license_author = self.license_author

        license_author_url: str | Unset
        if isinstance(self.license_author_url, Unset):
            license_author_url = UNSET
        else:
            license_author_url = self.license_author_url

        license_derivative_source_url: str | Unset
        if isinstance(self.license_derivative_source_url, Unset):
            license_derivative_source_url = UNSET
        else:
            license_derivative_source_url = self.license_derivative_source_url

        is_ai_generated = self.is_ai_generated

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "exercise": exercise,
                "image": image,
            }
        )
        if is_main is not UNSET:
            field_dict["is_main"] = is_main
        if style is not UNSET:
            field_dict["style"] = style
        if license_ is not UNSET:
            field_dict["license"] = license_
        if license_title is not UNSET:
            field_dict["license_title"] = license_title
        if license_object_url is not UNSET:
            field_dict["license_object_url"] = license_object_url
        if license_author is not UNSET:
            field_dict["license_author"] = license_author
        if license_author_url is not UNSET:
            field_dict["license_author_url"] = license_author_url
        if license_derivative_source_url is not UNSET:
            field_dict["license_derivative_source_url"] = license_derivative_source_url
        if is_ai_generated is not UNSET:
            field_dict["is_ai_generated"] = is_ai_generated

        return field_dict

    def to_multipart(self) -> types.RequestFiles:
        files: types.RequestFiles = []

        files.append(("exercise", (None, str(self.exercise).encode(), "text/plain")))

        files.append(("image", self.image.to_tuple()))

        if not isinstance(self.is_main, Unset):
            files.append(("is_main", (None, str(self.is_main).encode(), "text/plain")))

        if not isinstance(self.style, Unset):
            files.append(
                ("style", (None, str(self.style.value).encode(), "text/plain"))
            )

        if not isinstance(self.license_, Unset):
            files.append(("license", (None, str(self.license_).encode(), "text/plain")))

        if not isinstance(self.license_title, Unset):
            files.append(
                (
                    "license_title",
                    (None, str(self.license_title).encode(), "text/plain"),
                )
            )

        if not isinstance(self.license_object_url, Unset):
            if isinstance(self.license_object_url, str):
                files.append(
                    (
                        "license_object_url",
                        (None, str(self.license_object_url).encode(), "text/plain"),
                    )
                )

        if not isinstance(self.license_author, Unset):
            files.append(
                (
                    "license_author",
                    (None, str(self.license_author).encode(), "text/plain"),
                )
            )

        if not isinstance(self.license_author_url, Unset):
            if isinstance(self.license_author_url, str):
                files.append(
                    (
                        "license_author_url",
                        (None, str(self.license_author_url).encode(), "text/plain"),
                    )
                )

        if not isinstance(self.license_derivative_source_url, Unset):
            if isinstance(self.license_derivative_source_url, str):
                files.append(
                    (
                        "license_derivative_source_url",
                        (
                            None,
                            str(self.license_derivative_source_url).encode(),
                            "text/plain",
                        ),
                    )
                )

        if not isinstance(self.is_ai_generated, Unset):
            files.append(
                (
                    "is_ai_generated",
                    (None, str(self.is_ai_generated).encode(), "text/plain"),
                )
            )

        for prop_name, prop in self.additional_properties.items():
            files.append((prop_name, (None, str(prop).encode(), "text/plain")))

        return files

    @classmethod
    def from_dict(cls, src_dict: Mapping[str, Any]) -> Self:
        d = dict(src_dict)
        exercise = d.pop("exercise")

        image = File(payload=BytesIO(d.pop("image")))

        is_main = d.pop("is_main", UNSET)

        _style = d.pop("style", UNSET)
        style: StyleEnum | Unset
        if isinstance(_style, Unset):
            style = UNSET
        else:
            style = StyleEnum(_style)

        license_ = d.pop("license", UNSET)

        license_title = d.pop("license_title", UNSET)

        def _parse_license_object_url(data: object) -> str | Unset:
            if isinstance(data, Unset):
                return data
            return cast(str | Unset, data)

        license_object_url = _parse_license_object_url(
            d.pop("license_object_url", UNSET)
        )

        license_author = d.pop("license_author", UNSET)

        def _parse_license_author_url(data: object) -> str | Unset:
            if isinstance(data, Unset):
                return data
            return cast(str | Unset, data)

        license_author_url = _parse_license_author_url(
            d.pop("license_author_url", UNSET)
        )

        def _parse_license_derivative_source_url(data: object) -> str | Unset:
            if isinstance(data, Unset):
                return data
            return cast(str | Unset, data)

        license_derivative_source_url = _parse_license_derivative_source_url(
            d.pop("license_derivative_source_url", UNSET)
        )

        is_ai_generated = d.pop("is_ai_generated", UNSET)

        exercise_image_request = cls(
            exercise=exercise,
            image=image,
            is_main=is_main,
            style=style,
            license_=license_,
            license_title=license_title,
            license_object_url=license_object_url,
            license_author=license_author,
            license_author_url=license_author_url,
            license_derivative_source_url=license_derivative_source_url,
            is_ai_generated=is_ai_generated,
        )

        exercise_image_request.additional_properties = d
        return exercise_image_request

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
